name: Create DataPower yaml files
on: [push]
jobs:
  DataPower_Yaml_Job1:
    name: DataPower yaml Job
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@v1
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: ls -a
      - name: Run script
        run: |
          chmod +x ./yaml-creation.sh
          sh ./yaml-creation.sh
      - run: echo "ğŸ This job's status is ${{ job.status }}."