name: Create DataPower yaml files
on: [push]
jobs:
  DataPower_Yaml_Job1:
    name: DataPower yaml Job
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: |
          cd ..
          ls -a
      - run: |
          cd ~
          ls -a
      - name: Run script
        run: sh ${{ github.workspace }}/yaml-creation.sh
      - run: echo "ğŸ This job's status is ${{ job.status }}."